# --- Configuración de Build para Producción ---
# Esta sección le dice a Netlify cómo construir tu sitio para subirlo a internet.
[build]
  # El comando que Netlify debe ejecutar para construir el proyecto.
  # Para proyectos con Vite, es "npm run build".
  command = "npm run build"

  # El directorio donde se guarda el sitio web ya construido.
  # Para proyectos con Vite, el resultado siempre está en la carpeta "dist".
  publish = "dist"

  # El directorio donde están tus funciones de servidor (backend).
  functions = "netlify/functions"

  # --- ¡ESTA ES LA LÍNEA CLAVE PARA EL ERROR ACTUAL! ---
  # Le dice a Netlify qué versión de Node.js debe usar para construir tu proyecto.
  # El error pide '>=20.0.0', así que usamos "20" para asegurar la compatibilidad.
  environment = { NODE_VERSION = "20" }


# --- Configuración para Single Page Application (SPA) ---
# Esta regla es ESENCIAL para que las rutas de tu aplicación funcionen correctamente.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200