# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

# --- AÑADE ESTA SECCIÓN ---
[functions]
  directory = "netlify/functions"
# -------------------------

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200